### ISSUE TITLE
Trouble with T1E and power tests when I have no covariates

### ISSUE THREAD

**Issue by acannis** [qlu-lab/QUAIL#1]
Hello. I'm having trouble running T1E and power tests with QUAIL. 

I've simulated data to test T1E in which there is a main genetic effect, but no variance effect: 
<img width="128" alt="image" src="https://user-images.githubusercontent.com/31316212/183699317-740bcad3-cd24-41be-8b19-c4e1a1ec5e6d.png">

I've also simulated data to test power in which there is a genetic effect, an environmental effect, and an interaction effect (w): 
<img width="234" alt="image" src="https://user-images.githubusercontent.com/31316212/183699596-46a1f9c7-7015-4dbe-a8f1-21cb7bcdcc0d.png">

My problem seems to occur in the covariate file, which is required in the code or it will throw an error. In this simulated data I don't have any covariates I want to adjust for, so I've tried 1) including only the ID columns (this throws an error), 2) including a dummy covariate with only values of "1", 

<img width="164" alt="image" src="https://user-images.githubusercontent.com/31316212/183701948-7a5cf498-642a-4940-8fc9-ce05bc0dc5f4.png">
<img width="277" alt="image" src="https://user-images.githubusercontent.com/31316212/183701983-7425529b-7c7a-48cd-a41e-ba118b3f9e87.png">

and 3) including a dummy covariate with values of "1" and changing the equation 
<img width="544" alt="image" src="https://user-images.githubusercontent.com/31316212/183700995-7cf98b9b-9b49-4315-bff7-8f5672a42301.png"> in the Obtain_rank_score.R script to 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/31316212/183700929-a5680770-46cf-44d8-a142-f081a4bcf717.png">. None of these options give me proper T1E and power results. 

Can you please help me find the proper setup for the situation in which there are no covariates?
Thanks, Aubrey

p.s. I have tested the same data with other methods (though without the covariate file since they do not require one), and the T1E and power results are as expected. This confirms to me that the problem is with the covariate file.

**Comment by jmiao24** [comment]
Hi acannis,

Could you please share the data with me so I can try to find out what the problem is? You can either post it here or send me via email to jmiao24@wisc.edu.

Best,
Jiacheng

**Comment by jmiao24** [comment]
Hi acannis,

FYI, I just added a folder called `simulations` in the Github. It contains the functions used for QUAIL simulations w/wo covariates. You can directly source these R file and use `QUAIL(x, y)` or `QUAIL(x, y, covar)` to run the simulations.  I have also provided an example file to run the simulation.

Please let me know If you are still having trouble running the simulation

Best,
Jiacheng

**Comment by acannis** [comment]
Hi Jiacheng, 
Apologies for dropping the ball on this. Here are simulated data for testing T1E - I broke them into chunks to accommodate size limitations. The chi-squared outcomes are generally the most problematic, though I've had trouble running about 15% of the normal and t outcomes as well. 
Best,
Aubrey 

[covars0.005_SIM1-500.zip](https://github.com/qlu-lab/QUAIL/files/9480894/covars0.005_SIM1-500.zip)
[covars0.005_SIM501-1000.zip](https://github.com/qlu-lab/QUAIL/files/9480903/covars0.005_SIM501-1000.zip)
[covars0.01-SIM1-500.zip](https://github.com/qlu-lab/QUAIL/files/9481888/covars0.01-SIM1-500.zip)
[covars0.01-SIM501-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481889/covars0.01-SIM501-1000.zip)
[covars0.02_SIM1-500.zip](https://github.com/qlu-lab/QUAIL/files/9481890/covars0.02_SIM1-500.zip)
[covars0.02_SIM501-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481891/covars0.02_SIM501-1000.zip)
[covars0.03_SIM1-500.zip](https://github.com/qlu-lab/QUAIL/files/9481894/covars0.03_SIM1-500.zip)
[covars0.03_SIM501-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481895/covars0.03_SIM501-1000.zip)
[covars0.04_SIM1-500.zip](https://github.com/qlu-lab/QUAIL/files/9481898/covars0.04_SIM1-500.zip)
[covars0.04_SIM501-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481899/covars0.04_SIM501-1000.zip)
[covars0.05_SIM1-500.zip](https://github.com/qlu-lab/QUAIL/files/9481903/covars0.05_SIM1-500.zip)
[covars0.05_SIM501-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481908/covars0.05_SIM501-1000.zip)

[genos0.005_SIM1-400.zip](https://github.com/qlu-lab/QUAIL/files/9481909/genos0.005_SIM1-400.zip)
[genos0.005_SIM701-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481911/genos0.005_SIM701-1000.zip)
[genos0.005_SIM401-700.zip](https://github.com/qlu-lab/QUAIL/files/9481910/genos0.005_SIM401-700.zip)
[genos0.01_SIM1-400.zip](https://github.com/qlu-lab/QUAIL/files/9481912/genos0.01_SIM1-400.zip)
[genos0.01_SIM401-700.zip](https://github.com/qlu-lab/QUAIL/files/9481914/genos0.01_SIM401-700.zip)
[genos0.01_SIM701-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481917/genos0.01_SIM701-1000.zip)
[genos0.02_SIM1-400.zip](https://github.com/qlu-lab/QUAIL/files/9481920/genos0.02_SIM1-400.zip)
[genos0.02_SIM401-700.zip](https://github.com/qlu-lab/QUAIL/files/9481921/genos0.02_SIM401-700.zip)
[genos0.02_SIM701-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481923/genos0.02_SIM701-1000.zip)
[genos0.03_SIM1-400.zip](https://github.com/qlu-lab/QUAIL/files/9481924/genos0.03_SIM1-400.zip)
[genos0.03_SIM401-700.zip](https://github.com/qlu-lab/QUAIL/files/9481925/genos0.03_SIM401-700.zip)
[genos0.03_SIM701-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481927/genos0.03_SIM701-1000.zip)
[genos0.04_SIM1-400.zip](https://github.com/qlu-lab/QUAIL/files/9481936/genos0.04_SIM1-400.zip)
[genos0.04_SIM401-700.zip](https://github.com/qlu-lab/QUAIL/files/9481938/genos0.04_SIM401-700.zip)
[genos0.04_SIM701-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481940/genos0.04_SIM701-1000.zip)
[genos0.05_SIM1-400.zip](https://github.com/qlu-lab/QUAIL/files/9481944/genos0.05_SIM1-400.zip)
[genos0.05_SIM401-700.zip](https://github.com/qlu-lab/QUAIL/files/9481945/genos0.05_SIM401-700.zip)
[genos0.05_SIM701-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481947/genos0.05_SIM701-1000.zip)

[phenos0.005_SIM1-50.zip](https://github.com/qlu-lab/QUAIL/files/9481948/phenos0.005_SIM1-50.zip)
[phenos0.005_SIM51-100.zip](https://github.com/qlu-lab/QUAIL/files/9481949/phenos0.005_SIM51-100.zip)
[phenos0.005_SIM101-150.zip](https://github.com/qlu-lab/QUAIL/files/9481950/phenos0.005_SIM101-150.zip)
[phenos0.005_SIM151-200.zip](https://github.com/qlu-lab/QUAIL/files/9481951/phenos0.005_SIM151-200.zip)
[phenos0.005_SIM201-250.zip](https://github.com/qlu-lab/QUAIL/files/9481952/phenos0.005_SIM201-250.zip)
[phenos0.005_SIM251-300.zip](https://github.com/qlu-lab/QUAIL/files/9481953/phenos0.005_SIM251-300.zip)
[phenos0.005_SIM301-350.zip](https://github.com/qlu-lab/QUAIL/files/9481954/phenos0.005_SIM301-350.zip)
[phenos0.005_SIM351-400.zip](https://github.com/qlu-lab/QUAIL/files/9481956/phenos0.005_SIM351-400.zip)
[phenos0.005_SIM401-450.zip](https://github.com/qlu-lab/QUAIL/files/9481957/phenos0.005_SIM401-450.zip)
[phenos0.005_SIM451-500.zip](https://github.com/qlu-lab/QUAIL/files/9481958/phenos0.005_SIM451-500.zip)
[phenos0.005_SIM501-550.zip](https://github.com/qlu-lab/QUAIL/files/9481959/phenos0.005_SIM501-550.zip)
[phenos0.005_SIM551-600.zip](https://github.com/qlu-lab/QUAIL/files/9481960/phenos0.005_SIM551-600.zip)
[phenos0.005_SIM601-650.zip](https://github.com/qlu-lab/QUAIL/files/9481961/phenos0.005_SIM601-650.zip)
[phenos0.005_SIM651-700.zip](https://github.com/qlu-lab/QUAIL/files/9481962/phenos0.005_SIM651-700.zip)
[phenos0.005_SIM701-750.zip](https://github.com/qlu-lab/QUAIL/files/9481965/phenos0.005_SIM701-750.zip)
[phenos0.005_SIM751-800.zip](https://github.com/qlu-lab/QUAIL/files/9481966/phenos0.005_SIM751-800.zip)
[phenos0.005_SIM801-850.zip](https://github.com/qlu-lab/QUAIL/files/9481967/phenos0.005_SIM801-850.zip)
[phenos0.005_SIM851-900.zip](https://github.com/qlu-lab/QUAIL/files/9481968/phenos0.005_SIM851-900.zip)
[phenos0.005_SIM901-950.zip](https://github.com/qlu-lab/QUAIL/files/9481970/phenos0.005_SIM901-950.zip)
[phenos0.005_SIM951-1000.zip](https://github.com/qlu-lab/QUAIL/files/9481971/phenos0.005_SIM951-1000.zip)
[phenos0.01_SIM1-50.zip](https://github.com/qlu-lab/QUAIL/files/9481977/phenos0.01_SIM1-50.zip)
[phenos0.01_SIM51-100.zip](https://github.com/qlu-lab/QUAIL/files/9481979/phenos0.01_SIM51-100.zip)
[phenos0.01_SIM101-150.zip](https://github.com/qlu-lab/QUAIL/files/9481980/phenos0.01_SIM101-150.zip)
[phenos0.01_SIM151-200.zip](https://github.com/qlu-lab/QUAIL/files/9481981/phenos0.01_SIM151-200.zip)
[phenos0.01_SIM201-250.zip](https://github.com/qlu-lab/QUAIL/files/9481983/phenos0.01_SIM201-250.zip)
[phenos0.01_SIM251-300.zip](https://github.com/qlu-lab/QUAIL/files/9481984/phenos0.01_SIM251-300.zip)
[phenos0.01_SIM301-350.zip](https://github.com/qlu-lab/QUAIL/files/9481985/phenos0.01_SIM301-350.zip)
[phenos0.01_SIM351-400.zip](https://github.com/qlu-lab/QUAIL/files/9481986/phenos0.01_SIM351-400.zip)
[phenos0.01_SIM401-450.zip](https://github.com/qlu-lab/QUAIL/files/9481987/phenos0.01_SIM401-450.zip)
[phenos0.01_SIM451-500.zip](https://github.com/qlu-lab/QUAIL/files/9481990/phenos0.01_SIM451-500.zip)
[phenos0.01_SIM501-550.zip](https://github.com/qlu-lab/QUAIL/files/9481992/phenos0.01_SIM501-550.zip)
[phenos0.01_SIM551-600.zip](https://github.com/qlu-lab/QUAIL/files/9481994/phenos0.01_SIM551-600.zip)
[phenos0.01_SIM601-650.zip](https://github.com/qlu-lab/QUAIL/files/9481995/phenos0.01_SIM601-650.zip)
[phenos0.01_SIM651-700.zip](https://github.com/qlu-lab/QUAIL/files/9481997/phenos0.01_SIM651-700.zip)
[phenos0.01_SIM701-750.zip](https://github.com/qlu-lab/QUAIL/files/9481999/phenos0.01_SIM701-750.zip)
[phenos0.01_SIM751-800.zip](https://github.com/qlu-lab/QUAIL/files/9482000/phenos0.01_SIM751-800.zip)
[phenos0.01_SIM801-850.zip](https://github.com/qlu-lab/QUAIL/files/9482001/phenos0.01_SIM801-850.zip)
[phenos0.01_SIM851-900.zip](https://github.com/qlu-lab/QUAIL/files/9482002/phenos0.01_SIM851-900.zip)
[phenos0.01_SIM901-951.zip](https://github.com/qlu-lab/QUAIL/files/9482003/phenos0.01_SIM901-951.zip)
[phenos0.01_SIM951-1000.zip](https://github.com/qlu-lab/QUAIL/files/9482005/phenos0.01_SIM951-1000.zip)
[phenos0.02_SIM1-50.zip](https://github.com/qlu-lab/QUAIL/files/9482009/phenos0.02_SIM1-50.zip)
[phenos0.02_SIM51_100.zip](https://github.com/qlu-lab/QUAIL/files/9482011/phenos0.02_SIM51_100.zip)
[phenos0.02_SIM101-150.zip](https://github.com/qlu-lab/QUAIL/files/9482013/phenos0.02_SIM101-150.zip)
[phenos0.02_SIM151-200.zip](https://github.com/qlu-lab/QUAIL/files/9482014/phenos0.02_SIM151-200.zip)
[phenos0.02_SIM201-250.zip](https://github.com/qlu-lab/QUAIL/files/9482016/phenos0.02_SIM201-250.zip)
[phenos0.02_SIM251-300.zip](https://github.com/qlu-lab/QUAIL/files/9482017/phenos0.02_SIM251-300.zip)
[phenos0.02_SIM301-350.zip](https://github.com/qlu-lab/QUAIL/files/9482018/phenos0.02_SIM301-350.zip)
[phenos0.02_SIM351-400.zip](https://github.com/qlu-lab/QUAIL/files/9482020/phenos0.02_SIM351-400.zip)
[phenos0.02_SIM401-450.zip](https://github.com/qlu-lab/QUAIL/files/9482021/phenos0.02_SIM401-450.zip)
[phenos0.02_SIM451-500.zip](https://github.com/qlu-lab/QUAIL/files/9482022/phenos0.02_SIM451-500.zip)
[phenos0.02_SIM501-550.zip](https://github.com/qlu-lab/QUAIL/files/9482023/phenos0.02_SIM501-550.zip)
[phenos0.02_SIM551-600.zip](https://github.com/qlu-lab/QUAIL/files/9482024/phenos0.02_SIM551-600.zip)
[phenos0.02_SIM601-650.zip](https://github.com/qlu-lab/QUAIL/files/9482025/phenos0.02_SIM601-650.zip)
[phenos0.02_SIM651-700.zip](https://github.com/qlu-lab/QUAIL/files/9482026/phenos0.02_SIM651-700.zip)
[phenos0.02_SIM701-750.zip](https://github.com/qlu-lab/QUAIL/files/9482028/phenos0.02_SIM701-750.zip)
[phenos0.02_SIM751-800.zip](https://github.com/qlu-lab/QUAIL/files/9482031/phenos0.02_SIM751-800.zip)
[phenos0.02_SIM801-850.zip](https://github.com/qlu-lab/QUAIL/files/9482033/phenos0.02_SIM801-850.zip)
[phenos0.02_SIM851-900.zip](https://github.com/qlu-lab/QUAIL/files/9482036/phenos0.02_SIM851-900.zip)
[phenos0.02_SIM901-950.zip](https://github.com/qlu-lab/QUAIL/files/9482039/phenos0.02_SIM901-950.zip)
[phenos0.02_SIM951-1000.zip](https://github.com/qlu-lab/QUAIL/files/9482040/phenos0.02_SIM951-1000.zip)
[phenos0.03_SIM1-50.zip](https://github.com/qlu-lab/QUAIL/files/9482042/phenos0.03_SIM1-50.zip)
[phenos0.03_SIM51-100.zip](https://github.com/qlu-lab/QUAIL/files/9482043/phenos0.03_SIM51-100.zip)
[phenos0.03_SIM101-150.zip](https://github.com/qlu-lab/QUAIL/files/9482045/phenos0.03_SIM101-150.zip)
[phenos0.03_SIM151-200.zip](https://github.com/qlu-lab/QUAIL/files/9482048/phenos0.03_SIM151-200.zip)
[phenos0.03_SIM201-250.zip](https://github.com/qlu-lab/QUAIL/files/9482050/phenos0.03_SIM201-250.zip)
[phenos0.03_SIM251-300.zip](https://github.com/qlu-lab/QUAIL/files/9482051/phenos0.03_SIM251-300.zip)
[phenos0.03_SIM301-350.zip](https://github.com/qlu-lab/QUAIL/files/9482054/phenos0.03_SIM301-350.zip)
[phenos0.03_SIM351-400.zip](https://github.com/qlu-lab/QUAIL/files/9482059/phenos0.03_SIM351-400.zip)
[phenos0.03_SIM401-450.zip](https://github.com/qlu-lab/QUAIL/files/9482061/phenos0.03_SIM401-450.zip)
[phenos0.03_SIM451-500.zip](https://github.com/qlu-lab/QUAIL/files/9482063/phenos0.03_SIM451-500.zip)
[phenos0.03_SIM501-550.zip](https://github.com/qlu-lab/QUAIL/files/9482064/phenos0.03_SIM501-550.zip)
[phenos0.03_SIM551-600.zip](https://github.com/qlu-lab/QUAIL/files/9482065/phenos0.03_SIM551-600.zip)
[phenos0.03_SIM601-650.zip](https://github.com/qlu-lab/QUAIL/files/9482066/phenos0.03_SIM601-650.zip)
[phenos0.03_SIM651-700.zip](https://github.com/qlu-lab/QUAIL/files/9482067/phenos0.03_SIM651-700.zip)
[phenos0.03_SIM701-750.zip](https://github.com/qlu-lab/QUAIL/files/9482068/phenos0.03_SIM701-750.zip)
[phenos0.03_SIM751-800.zip](https://github.com/qlu-lab/QUAIL/files/9482070/phenos0.03_SIM751-800.zip)
[phenos0.03_SIM801-850.zip](https://github.com/qlu-lab/QUAIL/files/9482073/phenos0.03_SIM801-850.zip)
[phenos0.03_SIM851-900.zip](https://github.com/qlu-lab/QUAIL/files/9482074/phenos0.03_SIM851-900.zip)
[phenos0.03_SIM901-950.zip](https://github.com/qlu-lab/QUAIL/files/9482075/phenos0.03_SIM901-950.zip)
[phenos0.03_SIM951-1000.zip](https://github.com/qlu-lab/QUAIL/files/9482076/phenos0.03_SIM951-1000.zip)
[phenos0.04_SIM1-50.zip](https://github.com/qlu-lab/QUAIL/files/9482083/phenos0.04_SIM1-50.zip)
[phenos0.04_SIM51-100.zip](https://github.com/qlu-lab/QUAIL/files/9482086/phenos0.04_SIM51-100.zip)
[phenos0.04_SIM101-150.zip](https://github.com/qlu-lab/QUAIL/files/9482087/phenos0.04_SIM101-150.zip)
[phenos0.04_SIM151-200.zip](https://github.com/qlu-lab/QUAIL/files/9482088/phenos0.04_SIM151-200.zip)
[phenos0.04_SIM201-250.zip](https://github.com/qlu-lab/QUAIL/files/9482089/phenos0.04_SIM201-250.zip)
[phenos0.04_SIM251-300.zip](https://github.com/qlu-lab/QUAIL/files/9482090/phenos0.04_SIM251-300.zip)
[phenos0.04_SIM301-350.zip](https://github.com/qlu-lab/QUAIL/files/9482091/phenos0.04_SIM301-350.zip)
[phenos0.04_SIM351-400.zip](https://github.com/qlu-lab/QUAIL/files/9482093/phenos0.04_SIM351-400.zip)
[phenos0.04_SIM401-450.zip](https://github.com/qlu-lab/QUAIL/files/9482095/phenos0.04_SIM401-450.zip)
[phenos0.04_SIM451-500.zip](https://github.com/qlu-lab/QUAIL/files/9482097/phenos0.04_SIM451-500.zip)
[phenos0.04_SIM501-550.zip](https://github.com/qlu-lab/QUAIL/files/9482098/phenos0.04_SIM501-550.zip)
[phenos0.04_SIM551-600.zip](https://github.com/qlu-lab/QUAIL/files/9482100/phenos0.04_SIM551-600.zip)
[phenos0.04_SIM601-650.zip](https://github.com/qlu-lab/QUAIL/files/9482102/phenos0.04_SIM601-650.zip)
[phenos0.04_SIM651-700.zip](https://github.com/qlu-lab/QUAIL/files/9482105/phenos0.04_SIM651-700.zip)
[phenos0.04_SIM701-750.zip](https://github.com/qlu-lab/QUAIL/files/9482109/phenos0.04_SIM701-750.zip)
[phenos0.04_SIM751-800.zip](https://github.com/qlu-lab/QUAIL/files/9482111/phenos0.04_SIM751-800.zip)
[phenos0.04_SIM801-850.zip](https://github.com/qlu-lab/QUAIL/files/9482113/phenos0.04_SIM801-850.zip)
[phenos0.04_SIM851-900.zip](https://github.com/qlu-lab/QUAIL/files/9482114/phenos0.04_SIM851-900.zip)
[phenos0.04_SIM901-950.zip](https://github.com/qlu-lab/QUAIL/files/9482115/phenos0.04_SIM901-950.zip)
[phenos0.04_SIM951-1000.zip](https://github.com/qlu-lab/QUAIL/files/9482116/phenos0.04_SIM951-1000.zip)
[phenos0.05_SIM1-50.zip](https://github.com/qlu-lab/QUAIL/files/9482121/phenos0.05_SIM1-50.zip)
[phenos0.05_SIM51-100.zip](https://github.com/qlu-lab/QUAIL/files/9482122/phenos0.05_SIM51-100.zip)
[phenos0.05_SIM101-150.zip](https://github.com/qlu-lab/QUAIL/files/9482123/phenos0.05_SIM101-150.zip)
[phenos0.05_SIM151-200.zip](https://github.com/qlu-lab/QUAIL/files/9482124/phenos0.05_SIM151-200.zip)
[phenos0.05_SIM201-250.zip](https://github.com/qlu-lab/QUAIL/files/9482125/phenos0.05_SIM201-250.zip)
[phenos0.05_SIM251-300.zip](https://github.com/qlu-lab/QUAIL/files/9482129/phenos0.05_SIM251-300.zip)
[phenos0.05_SIM301-350.zip](https://github.com/qlu-lab/QUAIL/files/9482132/phenos0.05_SIM301-350.zip)
[phenos0.05_SIM351-400.zip](https://github.com/qlu-lab/QUAIL/files/9482134/phenos0.05_SIM351-400.zip)
[phenos0.05_SIM401-450.zip](https://github.com/qlu-lab/QUAIL/files/9482136/phenos0.05_SIM401-450.zip)
[phenos0.05_SIM451-500.zip](https://github.com/qlu-lab/QUAIL/files/9482137/phenos0.05_SIM451-500.zip)
[phenos0.05_SIM501-550.zip](https://github.com/qlu-lab/QUAIL/files/9482139/phenos0.05_SIM501-550.zip)
[phenos0.05_SIM551-600.zip](https://github.com/qlu-lab/QUAIL/files/9482140/phenos0.05_SIM551-600.zip)
[phenos0.05_SIM601-650.zip](https://github.com/qlu-lab/QUAIL/files/9482141/phenos0.05_SIM601-650.zip)
[phenos0.05_SIM651-700.zip](https://github.com/qlu-lab/QUAIL/files/9482143/phenos0.05_SIM651-700.zip)
[phenos0.05_SIM701-750.zip](https://github.com/qlu-lab/QUAIL/files/9482145/phenos0.05_SIM701-750.zip)
[phenos0.05_SIM751-800.zip](https://github.com/qlu-lab/QUAIL/files/9482146/phenos0.05_SIM751-800.zip)
[phenos0.05_SIM801-850.zip](https://github.com/qlu-lab/QUAIL/files/9482149/phenos0.05_SIM801-850.zip)
[phenos0.05_SIM851-900.zip](https://github.com/qlu-lab/QUAIL/files/9482152/phenos0.05_SIM851-900.zip)
[phenos0.05_SIM901-950.zip](https://github.com/qlu-lab/QUAIL/files/9482153/phenos0.05_SIM901-950.zip)
[phenos0.05_SIM951-1000.zip](https://github.com/qlu-lab/QUAIL/files/9482155/phenos0.05_SIM951-1000.zip)

**Comment by jmiao24** [comment]
The simulations scripts have been provided in the Github.
